# Generated by Django 4.2.9 on 2024-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
